container:
  image: node:latest
test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  type_check_script: npm run type-check
  build_script: npm run build
  test_script: npm test